version: "3.5"

services:
  celery:
    container_name: celery
    networks:
      - local-network
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - rabbitmq
      
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    networks:
      - local-network
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: example
    ports:
      - 5672:5672
      - 15672:15672

networks:
  local-network:
    name: local-network
  